In [2]:
# pip install numpy
import numpy as np


# Creating numpy array

In [2]:
x = [1,2,3,4,5]
nx = np.array(x)

In [3]:
nx.ndim #

1

In [4]:
y = [[1,2,3],[4,5,6]]
ny= np.array(y)

In [5]:
ny.ndim

2

In [6]:
print(nx)

[1 2 3 4 5]


In [7]:
print(ny)

[[1 2 3]
 [4 5 6]]


In [8]:
nz= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
nz.ndim

2

In [10]:
nx.shape

(5,)

In [11]:
ny.shape

(2, 3)

In [12]:
nz.shape

(3, 3)

In [13]:
x= np.arange(-10,10,0.5)

In [14]:
print(x)

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5]


In [15]:
x.shape

(40,)

In [19]:
y = np.linspace(0,10,5) #print np.linspace(0,10,5, endpoint = False)  for not including endpoint
print(y) #linear space

[ 0.   2.5  5.   7.5 10. ]


In [20]:
a = np.random.rand(6)
print(a)


[0.69776235 0.47894641 0.53508964 0.49318722 0.32491854 0.50890709]


In [21]:
c = np.random.randint(0,101,(3,3)) #interger random value
print (c)

[[ 9 94 23]
 [28 40 66]
 [58 83 66]]


In [22]:
d = np.random.choice([1,2,5],(3,3))
print(d)

[[1 5 1]
 [2 5 1]
 [1 5 5]]


In [23]:
o = np.ones((3,3), dtype = int)
print (o)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
e = np.eye(6,dtype = int)
print(e)
 

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [25]:
np.diag(nx)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [30]:
c.transpose()
print(c.T)

[[ 9 28 58]
 [94 40 83]
 [23 66 66]]


In [31]:
c.size

9

In [32]:
c.dtype

dtype('int32')

In [33]:
x = np.array ([[6,9],[6,9]])
y = np.array ([[3,2],[1,3]])


In [34]:
print (x+y)

[[ 9 11]
 [ 7 12]]


In [35]:
x+5

array([[11, 14],
       [11, 14]])

In [36]:
x.dot(y) # dot is matrix multiplication

array([[27, 39],
       [27, 39]])

In [37]:
np.cross(x,y)


array([-15,   9])

In [38]:
np.sin(x)

array([[-0.2794155 ,  0.41211849],
       [-0.2794155 ,  0.41211849]])

In [42]:
x.argmax() # max number on which index

1

In [43]:
x.argmin() # min number on which index

0

In [44]:
r = np.random.randint(-101,101,(5,5))
r

array([[-24,  76, -85,  90,  63],
       [ -4,  61,  17,  89,  93],
       [ 62,  57,  74,  78, -78],
       [-52,  -9,  61, -52, -43],
       [-14, -80,  60, -55,  92]])

In [45]:
r.max()

93

In [46]:
r.min()

-85

In [47]:
print(r.sum(), r.mean(),r.std(),r.var(),r.prod())

477 19.08 61.52132638362083 3784.8736000000004 33554432


In [3]:
x = np.random.randint(0, 101, (3,3))
y = np.random.randint(0, 101, (3,3))
print(x, y, sep='\n\n')

[[84 20 61]
 [99 88 97]
 [78  8 98]]

[[37 47 55]
 [88 83 36]
 [31 36 44]]


In [4]:
x * y # hadamard product

array([[3108,  940, 3355],
       [8712, 7304, 3492],
       [2418,  288, 4312]])

In [5]:
x @ y # matrix product (dot product)

array([[ 6759,  7804,  8024],
       [14414, 15449, 12881],
       [ 6628,  7858,  8890]])

## numpy slicing (in 2D array)
arr[row_start:row_end, col_start:col_end]

In [6]:
# 10 x 5 matrix
a = np.random.randint(10, 100, (10,5))
a

array([[51, 34, 39, 64, 15],
       [88, 98, 48, 24, 79],
       [87, 64, 58, 50, 45],
       [36, 74, 17, 29, 35],
       [78, 39, 94, 65, 23],
       [95, 82, 65, 93, 24],
       [85, 86, 39, 60, 15],
       [34, 96, 52, 77, 85],
       [71, 99, 29, 78, 10],
       [80, 63, 25, 77, 11]])

In [7]:
# top 5 rows
print(a[:5])
# last 3 rows
print(a[-3:])

[[51 34 39 64 15]
 [88 98 48 24 79]
 [87 64 58 50 45]
 [36 74 17 29 35]
 [78 39 94 65 23]]
[[34 96 52 77 85]
 [71 99 29 78 10]
 [80 63 25 77 11]]


In [8]:
# 1 column
print(a[:, 1])
# first 3 columns
print(a[:, :3])
# last 3 columns
print(a[:, -3:])
# 0,2,4 columns
print(a[:, [0,2,4]])
# first 5 rows , first 3 columns
print(a[:5, :3])

[34 98 64 74 39 82 86 96 99 63]
[[51 34 39]
 [88 98 48]
 [87 64 58]
 [36 74 17]
 [78 39 94]
 [95 82 65]
 [85 86 39]
 [34 96 52]
 [71 99 29]
 [80 63 25]]
[[39 64 15]
 [48 24 79]
 [58 50 45]
 [17 29 35]
 [94 65 23]
 [65 93 24]
 [39 60 15]
 [52 77 85]
 [29 78 10]
 [25 77 11]]
[[51 39 15]
 [88 48 79]
 [87 58 45]
 [36 17 35]
 [78 94 23]
 [95 65 24]
 [85 39 15]
 [34 52 85]
 [71 29 10]
 [80 25 11]]
[[51 34 39]
 [88 98 48]
 [87 64 58]
 [36 74 17]
 [78 39 94]]
